#!/bin/bash

ENVFILE=.proxynodpi.env
if [ ! -f $ENVFILE ]; then
  echo -e "PACKAGES=SERVICE_NAME=proxynodpi\nSYSTEMD_SERVICE_NAME=proxynodpi.service\nSYSTEMD_DIR=/etc/systemd/system\nPYTHON_TARGET=python3.13\nRUNNER=proxy_runner.py\nVENV_DIR=venv\nLOGS_DIR=logs\nPIDS_DIR=pids\nREPO=Patttern/proxynodpi" > $ENVFILE
fi
source $ENVFILE

# Check for Debian-based OS
if [ ! "$(grep -Ei 'debian|buntu|mint' /proc/version)" ]; then
  echo 'Конфигураци программы не поддерживается на установленной системе'
  exit 1
fi

function installpack {
  exec=`which $PYTHON_TARGET`
  if [ -z "$exec" ]; then
    found=$(cat /etc/apt/sources.list.d/* | grep 'https://ppa.launchpadcontent.net/deadsnakes/ppa/')
    if [ -z "$found" ]; then
      sudo apt install -y software-properties-common
      sudo add-apt-repository ppa:deadsnakes/ppa
    fi
  fi
  sudo apt install -y $PYTHON_TARGET $PYTHON_TARGET-venv wget curl
}

function setup {
  echo 'Производится настройка программы'

  # Check for installed packages
  installpack

  # Check if runned as service and deinstall it
  installed=false
  systemctl list-unit-files $SYSTEMD_SERVICE_NAME &>/dev/null && installed=true
  if [ $installed = true ]; then
    deinstall
  fi

  # Stop standalone programm if runned
  stop

  # Setup programm
  currPath=`pwd`
  if [ -d "$currPath/${VENV_DIR}" ]; then
   rm -rf $currPath/${VENV_DIR}
  fi
  mkdir -p $currPath/$LOGS_DIR
  mkdir -p $currPath/$PIDS_DIR
  $exec -m venv $currPath/$VENV_DIR
  source $currPath/${VENV_DIR}/bin/activate
  python -m pip install --upgrade pip
  pip install --upgrade -r requirements.txt
  deactivate
  echo 'Настройка программы успешно произведена'
}

function installsysd {
  echo 'Производится установка сервиса'
  currPath=`pwd`
  cp $currPath/systemd/$SYSTEMD_SERVICE_NAME.sample $currPath/systemd/$SYSTEMD_SERVICE_NAME
  sed -i "s/__user__/$USER/g" $currPath/systemd/$SYSTEMD_SERVICE_NAME
  sed -i "s+__path__+$currPath+g" $currPath/systemd/$SYSTEMD_SERVICE_NAME
  sed -i "s/__runner__/$RUNNER/g" $currPath/systemd/$SYSTEMD_SERVICE_NAME
  sudo mv $currPath/systemd/$SYSTEMD_SERVICE_NAME $SYSTEMD_DIR/$SYSTEMD_SERVICE_NAME
  sudo systemctl enable $SYSTEMD_SERVICE_NAME
  sudo systemctl start $SYSTEMD_SERVICE_NAME
  systemctl status $SYSTEMD_SERVICE_NAME
  echo 'Установка успешно завершена'
}

function install {
  # Resetup program
  currPath=`pwd`
  if [ ! -f $currPath/${VENV_DIR}/bin/$PYTHON_TARGET ]; then
    setup
  fi

  # Install systemd service
  installed=false
  systemctl list-unit-files $SYSTEMD_SERVICE_NAME &>/dev/null && installed=true
  if [ $installed = true ]; then
    echo 'Программа уже установлена как сервис.'
    read -p "Желаете переустановить сервис? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] && installsysd || exit 0
  else
    installsysd
  fi
}

function deinstall {
  installed=true
  systemctl list-unit-files $SYSTEMD_SERVICE_NAME &>/dev/null && installed=true || installed=false
  if [ $installed = true ]; then
    echo 'Производится удаление сервиса'
    sudo systemctl stop $SYSTEMD_SERVICE_NAME
    sudo systemctl disable $SYSTEMD_SERVICE_NAME
    sudo rm $SYSTEMD_DIR/$SYSTEMD_SERVICE_NAME
    echo 'Удаление успешно завершено'
  else
    echo 'Программа не установлена как сервис'
  fi
}

function start {
  pid=`ps ax | grep python | grep $RUNNER | awk '{print $1}'`
  if [ -z "$pid" ]; then
    currPath=`pwd`
    source venv/bin/activate
    nohup python $RUNNER >/dev/null 2>&1 & echo $! > $currPath/${PIDS_DIR}/${SERVICE_NAME}.pid
  else
    echo 'Программа уже запущена'
  fi
}

function stop {
  currPath=`pwd`
  if [ -f "$currPath/${PIDS_DIR}/${SERVICE_NAME}.pid" ]; then
    pid=`cat $currPath/${PIDS_DIR}/${SERVICE_NAME}.pid`
    rm $currPath/${PIDS_DIR}/${SERVICE_NAME}.pid
  else
    pid=`ps ax | grep python | grep $RUNNER | awk '{print $1}'`
  fi
  if [ ! -z "$pid" ]; then
    sudo kill -9 $pid
  fi
}

function restart {
  stop
  start
}

function update {
  version
  release=$(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/$REPO/releases/latest")
  tag=$(echo "$release" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
  description=$(echo "$release" | grep '"body":' | sed -E 's/.*"([^"]+)".*/\1/')
  exec=`which $PYTHON_TARGET`
  currVersion=`$exec -c "print(__import__('proxyserver').__version__)"`
  if [ "$tag" = "v$currVersion" ]; then
    echo 'Установлена актуальная версия программы'
  else
    echo "Доступна новая версия программы: $tag"
    echo "Описание:"
    echo -e $description | sed 's/\\r\\n/\n/g'
    echo
    read -p "Желаете загрузить новую версию? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] && release || exit 0
  fi
}

function release {
  target=$(echo "$release" | grep '"tarball_url":' | sed -E 's/.*"([^"]+)".*/\1/')
  outfile=${SERVICE_NAME}_${tag}.tar.gz
  wget -q -O $outfile $target
  tar zxvf $outfile --strip-components 1
  rm $outfile
  setup
  installed=false
  systemctl list-unit-files $SYSTEMD_SERVICE_NAME &>/dev/null && installed=true
  if [ $installed = true ]; then
    sudo systemctl restart $SYSTEMD_SERVICE_NAME
  else
    read -p "Желаете установить программу как сервис? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] && installsysd || exit 0
  fi
}

function version {
  exec=`which $PYTHON_TARGET`
  currVersion=`$exec -c "print(__import__('proxyserver').__version__)"`
  currDate=`$exec -c "print(__import__('proxyserver').__updated__)"`
  echo "Proxy NoDPI v${currVersion} (${currDate})"
  echo
}

function help {
  version
  echo
  echo 'Основные команды:'
  echo '  setup - начальная настройка программы. Можно указать целевую версию Python вторым параметром.'
  echo '    Например, команда'
  echo '    ./service setup 3.11'
  echo '    произведет настройку программы на версию Python 3.11.'
  echo '    По умолчанию, 3.13'
  echo '  install - установить программу как systemd сервис'
  echo '  deinstall - удалить программу из systemd сервиса'
  echo '  start - запуск программы'
  echo '  stop - остановка программы'
  echo '  restart - перезапуск программы'
  echo '  update - обновить программу до актуальной версии'
  echo '  version - показать текущую версию программы'
  echo '  help - текущая справка'
  echo
}

case $1 in
  setup)
    arg=$2
    targetVersion=python${arg:-'3.13'}
    sed -i "s/^PYTHON_TARGET.*$/PYTHON_TARGET=$targetVersion/" $ENVFILE
    source $ENVFILE
    setup
    ;;
  install)
    install
    ;;
  deinstall)
    deinstall
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  update)
    update
    ;;
  version)
    version
    ;;
  help)
    help
    ;;
  *)
    help
    ;;
esac

exit 0
